default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: 3306

development:
  <<: *default
  database: cresce_cuts_ror_development

test:
  <<: *default
  database: cresce_cuts_ror_test
